import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Subho Ghosh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white text-black dark:bg-[#282C34] dark:text-white">
        <Header />
        <main className="text-red-500">hello</main>
      </div>
    </div>
  );
}
